server:
  port: 9093

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: myVerySecretKeyForCRMApplication123456789123456789
  expiration: 86400000
