server:
  port: 9092

spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/employee-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: myVerySecretKeyForCRMApplication123456789123456789
  expiration: 86400000